"""Convert a Blender collision model into an MJCF geoms-fragment for gsplat scenes.

Each mesh object becomes ONE <geom> -- boxes are read exactly (8 world corners
-> center + half extents, axis-aligned check, OBB fallback with a quaternion),
never merged, never convex-hulled. Merging pieces into one mesh is the mistake
that would fill a stairwell solid; this tool cannot do it.

Run UNDER blender (needs bpy):

    blender --background <model.blend> --python make_collision_xml.py -- \
        --out <scene_dir>/mjcf/<name>_collision.xml \
        [--exclude-prefix REF_ INSPECT_] [--include-collection GEO_slabs GEO_stairs]

The output holds <geom> lines only, meant to be included inside <worldbody>
of the scene MJCF (same shape as church_scene/mjcf/church_collision.xml).
Point-cloud / inspection helpers must live under an excluded prefix.
"""

import sys

import bpy
import numpy as np

EPS = 1e-6


def parse_args(argv):
    out, exclude, include = None, ["REF_", "INSPECT_"], []
    it = iter(range(len(argv)))
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--out":
            out = argv[i + 1]; i += 2
        elif a == "--exclude-prefix":
            exclude += argv[i + 1:]; i += 2
        elif a == "--include-collection":
            include += argv[i + 1:]; i += 2
        else:
            i += 1
    if out is None:
        raise SystemExit("--out is required")
    return out, exclude, include


def rotmat_to_quat_wxyz(r):
    """Shepperd's method; r is a 3x3 rotation matrix (numpy, float)."""
    tr = r[0, 0] + r[1, 1] + r[2, 2]
    if tr > 0:
        s = np.sqrt(tr + 1.0) * 2
        w = 0.25 * s
        x = (r[2, 1] - r[1, 2]) / s
        y = (r[0, 2] - r[2, 0]) / s
        z = (r[1, 0] - r[0, 1]) / s
    elif r[0, 0] > r[1, 1] and r[0, 0] > r[2, 2]:
        s = np.sqrt(1.0 + r[0, 0] - r[1, 1] - r[2, 2]) * 2
        w = (r[2, 1] - r[1, 2]) / s; x = 0.25 * s
        y = (r[0, 1] + r[1, 0]) / s; z = (r[0, 2] + r[2, 0]) / s
    elif r[1, 1] > r[2, 2]:
        s = np.sqrt(1.0 + r[1, 1] - r[0, 0] - r[2, 2]) * 2
        w = (r[0, 2] - r[2, 0]) / s; x = (r[0, 1] + r[1, 0]) / s
        y = 0.25 * s; z = (r[1, 2] + r[2, 1]) / s
    else:
        s = np.sqrt(1.0 + r[2, 2] - r[0, 0] - r[1, 1]) * 2
        w = (r[1, 0] - r[0, 1]) / s; x = (r[0, 2] + r[2, 0]) / s
        y = (r[1, 2] + r[2, 1]) / s; z = 0.25 * s
    q = np.array([w, x, y, z])
    return q / np.linalg.norm(q)


def box_from_object(obj):
    """Exact box (center, half_extents, quat_wxyz) of an 8-vertex object.

    World-axis-aligned -> identity quat read straight off the world corners.
    Rotated/scaled -> local bbox carried through the object's world matrix
    (exact when the mesh itself is a box, which the 8-vertex check guarantees).
    """
    corners_world = np.array([obj.matrix_world @ v.co for v in obj.data.vertices])
    if len(corners_world) != 8:
        return None
    if all(len(np.unique(corners_world[:, i].round(6))) <= 2 for i in range(3)):
        lo = corners_world.min(0); hi = corners_world.max(0)
        return (lo + hi) / 2, (hi - lo) / 2, np.array([1.0, 0, 0, 0])
    m = np.array(obj.matrix_world)
    local = np.array([v.co for v in obj.data.vertices])
    lo, hi = local.min(0), local.max(0)
    center_h = np.append((lo + hi) / 2, 1.0)
    center = (m @ center_h)[:3]
    rot = m[:3, :3] / np.linalg.norm(m[:3, :3], axis=0)  # strip scale per column
    half = (hi - lo) / 2 * np.abs(np.linalg.norm(m[:3, :3], axis=0))
    return center, half, rotmat_to_quat_wxyz(rot)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    out_path, exclude, include = parse_args(argv)

    objs = [o for o in bpy.data.objects if o.type == "MESH"]
    if include:
        keep = set()
        for coll in bpy.data.collections:
            if coll.name in include:
                keep |= {o.name for o in coll.objects}
        objs = [o for o in objs if o.name in keep]
    objs = [o for o in objs if not o.name.startswith(tuple(exclude))]

    lines, skipped, boxes = [], [], []
    for o in sorted(objs, key=lambda x: x.name):
        box = box_from_object(o)
        if box is None:
            skipped.append(o.name)
            continue
        c, h, q = box
        boxes.append((o.name, c, h))
        quat = "" if abs(q[0] - 1) < 1e-9 else f' quat="{q[0]:.6f} {q[1]:.6f} {q[2]:.6f} {q[3]:.6f}"'
        lines.append(
            f'  <geom name="{o.name}" type="box" group="0" '
            f'size="{h[0]:.6f} {h[1]:.6f} {h[2]:.6f}" '
            f'pos="{c[0]:.6f} {c[1]:.6f} {c[2]:.6f}"{quat} '
            f'rgba="0.78 0.72 0.60 1" contype="1" conaffinity="1" />'
        )

    blend = bpy.data.filepath
    with open(out_path, "w") as f:
        f.write(f"<!-- generated by gsplat/tools/make_collision_xml.py from\n"
                f"     {blend}\n"
                f"     {len(lines)} box geoms, one per Blender object (exact, never merged);\n"
                f"     do not edit by hand. Included inside <worldbody> of scene.xml. -->\n")
        f.write("\n".join(lines) + "\n")

    zs = np.array([c[2] + h[2] for _, c, h in boxes])
    print(f"geoms: {len(lines)}  skipped (non-box): {skipped}")
    print(f"extent  x: {min(c[0]-h[0] for _,c,h in boxes):.2f}..{max(c[0]+h[0] for _,c,h in boxes):.2f}  "
          f"y: {min(c[1]-h[1] for _,c,h in boxes):.2f}..{max(c[1]+h[1] for _,c,h in boxes):.2f}  "
          f"z: {min(c[2]-h[2] for _,c,h in boxes):.2f}..{zs.max():.2f}")
    print(f"wrote {out_path}")


main()
