#!/usr/bin/env python3
"""One-shot generator for gazebo/worlds/stairs.sdf (switchback staircase world).

Two flights (6 steps each, riser 0.08 / tread 0.35, 1.4 m wide) joined by a
1.4 m turning platform; flight 1 climbs along +x, the turn is +90 deg (left),
flight 2 climbs along +y. Steps are solid ground-to-tread boxes (stable
contacts), plus low side rails and flanking crate-anchor walls. Rerun and
diff after tuning riser/tread. Same base skeleton as yard.sdf.
"""
import math

RISE, TREAD, WIDTH = 0.15, 0.28, 1.4  # 常用室内楼梯: 踢面150mm 踏面280mm
N = 8                       # steps per flight (flight rise: 1.2 m)
X0 = 2.0                    # flight-1 first riser foot line
PLAT = 1.4                  # turning platform length
F1_X0, F1_X1 = X0, X0 + N * TREAD           # 2.0 .. 4.1
PL_X0, PL_X1 = F1_X1, F1_X1 + PLAT          # 4.1 .. 5.5
Y0 = WIDTH / 2                              # 0.7, flight-2 starts north of it
F2_Y0, F2_Y1 = Y0, Y0 + N * TREAD           # 0.7 .. 2.8
TP_Y0, TP_Y1 = F2_Y1, F2_Y1 + PLAT          # 2.8 .. 4.2
H1 = N * RISE                               # 0.48
H2 = 2 * N * RISE                           # 0.96
RT = 0.05                                   # rail thickness
RH1, RH2 = H1 + 0.10, H2 + 0.10             # rail heights


def box(name, x, y, z, sx, sy, sz, tex=None, color=None):
    mat = ""
    if tex:
        mat = (f'<material><diffuse>1 1 1 1</diffuse><specular>0.05 0.05 0.05 1</specular>'
               f'<pbr><metal><albedo_map>model://textures/{tex}</albedo_map>'
               f'<roughness>0.95</roughness><metalness>0.0</metalness></metal></pbr></material>')
    elif color:
        mat = (f'<material><ambient>{color} 1</ambient><diffuse>{color} 1</diffuse></material>')
    return f'''      <collision name="col_{name}">
        <pose>{x:.4f} {y:.4f} {z:.4f} 0 0 0</pose>
        <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
        <surface><friction><ode><mu>1.2</mu><mu2>1.2</mu2></ode></friction></surface>
      </collision>
      <visual name="vis_{name}">
        <pose>{x:.4f} {y:.4f} {z:.4f} 0 0 0</pose>
        <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>{mat}
      </visual>'''


links = []
# flight 1: solid steps along +x, climbing to H1
for i in range(N):
    cx = F1_X0 + (i + 0.5) * TREAD
    h = (i + 1) * RISE
    links.append(box(f"f1_s{i}", cx, 0.0, h / 2, TREAD, WIDTH, h, "STAIRS_Albedo.png"))
# turning platform at H1
links.append(box("plat1", (PL_X0 + PL_X1) / 2, 0.0, H1 / 2,
                 PL_X1 - PL_X0, WIDTH, H1, "STAIRS_Albedo.png"))
# flight 2: solid steps along +y, from H1 to H2
for i in range(N):
    cy = F2_Y0 + (i + 0.5) * TREAD
    h = H1 + (i + 1) * RISE
    links.append(box(f"f2_s{i}", (PL_X0 + PL_X1) / 2, cy, h / 2, WIDTH, TREAD, h, "STAIRS_Albedo.png"))
# top platform at H2
links.append(box("plat2", (PL_X0 + PL_X1) / 2, (TP_Y0 + TP_Y1) / 2, H2 / 2,
                 WIDTH, TP_Y1 - TP_Y0, H2, "STAIRS_Albedo.png"))
# rails: flight-1 sides, then flight-2 sides (above deck level)
links.append(box("rail_f1_w", (F1_X0 + PL_X1) / 2, -WIDTH / 2 - RT / 2, RH1 / 2,
                 PL_X1 - F1_X0, RT, RH1, color="0.45 0.46 0.48"))
links.append(box("rail_f1_e", (F1_X0 + F1_X1) / 2, WIDTH / 2 + RT / 2, RH1 / 2,
                 F1_X1 - F1_X0, RT, RH1, color="0.45 0.46 0.48"))
links.append(box("rail_f2_w", PL_X0 - RT / 2, (F2_Y0 + TP_Y1) / 2, RH2 / 2,
                 RT, TP_Y1 - F2_Y0, RH2, color="0.45 0.46 0.48"))
links.append(box("rail_f2_e", PL_X1 + RT / 2, (F2_Y0 + TP_Y1) / 2, RH2 / 2,
                 RT, TP_Y1 - F2_Y0, RH2, color="0.45 0.46 0.48"))

# flanking crate anchor walls (yard vocabulary): two walls beside the
# approach, one wall facing the top platform
crates = []
k = 0
for row, (cx0, cy) in enumerate([(-1.0, -2.4), (-1.0, 2.4), (6.4, 3.4)]):
    for j in range(3):
        tex = f"crate_{(row * 3 + j) % 8}.png"
        x = cx0 + j * 1.288
        crates.append(box(f"crate{k:02d}", x, cy, 0.644, 1.288, 1.288, 1.288, tex))
        k += 1

sdf = f'''<?xml version="1.0" ?>
<!-- Switchback staircase: two flights (8 steps each, riser {RISE} m / tread {TREAD} m,
     {WIDTH} m wide) joined by a {PLAT} m turning platform; flight 1 climbs +x, turn
     left 90 deg, flight 2 climbs +y to {H2} m. Solid ground-to-tread steps with
     concrete nosing texture (gen_textures STAIRS_Albedo) for step-edge SLAM
     features; low rails keep the trot on deck; crate walls = yard-style
     far-field stereo anchors. Generated by tools note in git history; tune
     RISE/TREAD in the generator and re-emit after physics tests.
     Robots spawn by type at run time (gazebo/robots/go2: (0, 0, 0.31) facing +x). -->
<sdf version="1.9">
  <world name="stairs">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <scene>
      <ambient>1 1 1 1</ambient>
      <background>0.3 0.7 0.9 1</background>
      <shadows>0</shadows>
      <grid>1</grid>
    </scene>

    <light name="sun" type="directional">
      <pose>0 0 10 0 0 0</pose>
      <cast_shadows>false</cast_shadows>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>-0.3 0.3 -1</direction>
    </light>

    <!-- visual-only ceiling: same rationale as yard (open sky kills stereo) -->
    <model name="sky_shell">
      <static>1</static>
      <link name="link">
        <visual name="ceiling">
          <pose>0 0 12 0 0 0</pose>
          <geometry><plane><normal>0 0 -1</normal><size>220 160</size></plane></geometry>
          <material>
            <ambient>0.6 0.6 0.6 1</ambient>
            <diffuse>0.6 0.6 0.6 1</diffuse>
          </material>
        </visual>
      </link>
    </model>

    <model name="ground_plane">
      <static>1</static>
      <pose>0 0 0.002 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <surface>
            <friction><ode/></friction>
            <bounce/>
            <contact/>
          </surface>
        </collision>
        <visual name="floor_visual">
          <pose>0 0 -0.011 0 0 0</pose>
          <geometry><box><size>40 40 0.02</size></box></geometry>
          <material>
            <diffuse>1 1 1 1</diffuse>
            <specular>0.05 0.05 0.05 1</specular>
            <pbr>
              <metal>
                <albedo_map>model://textures/FLOOR_Albedo.png</albedo_map>
                <roughness>0.95</roughness>
                <metalness>0.0</metalness>
              </metal>
            </pbr>
          </material>
        </visual>
      </link>
    </model>

    <model name="stairs_switchback">
      <static>1</static>
      <pose>0 0 0 0 0 0</pose>
      <link name="link">
{chr(10).join(links)}
      </link>
    </model>

    <model name="anchor_walls">
      <static>1</static>
      <pose>0 0 0 0 0 0</pose>
      <link name="link">
{chr(10).join(crates)}
      </link>
    </model>
  </world>
</sdf>
'''
print(sdf)
print(f"# geometry: flight1 x[{F1_X0},{F1_X1}] top {H1}; flight2 y[{F2_Y0},{F2_Y1}] top {H2}",
      file=__import__('sys').stderr)
